version: '2'
services:

  buildbot:
    image: buildbot/buildbot-master:master
    env_file: db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://github.com/gentoo/Gentoo_kernelCI/archive/master.tar.gz
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://localhost:8080/
        - BUILDBOT_WEB_PORT=8080
        - WEB_AUTHS=test:test
        - WORKERS=kernelci:pass
        - BUILDBOT_STATUS_TOKEN=example
        - TCP_PORTS=8080,9989
    links:
      - db
    expose:
        - 8080
        - 9989

  db:
    image: "postgres:11.4-alpine"
    env_file: db.env
    expose:
        - 5432

  worker:
    image: buildbot/buildbot-worker:master
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: kernelci
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
        - buildbot
