version: '3'
services:

  buildbot:
    build: GBuildbot-master
    env_file: db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://github.com/GKernelCI/GBuildbot/archive/master.tar.gz
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=https://kernel1.amd64.dev.gentoo.org
        - WWW_AUTH_USER=web_auth_user
        - WWW_AUTH_PASWD=web_auth_password
        - GKERNELCI_URL=https://kernel1.amd64.dev.gentoo.org/
        - GKERNELCI_TITLE_URL=https://wiki.gentoo.org/wiki/Project:Kernel
        - GKERNELCI_TITLE=Gentoo Kernel
        - GHELPER_REPOURL=https://github.com/GKernelCI/Ghelper.git
        - GHELPER_BRANCH=master
        - MAIL_PASSWORD=mail_password
        - WORKER_NAME=worker_name
        - WORKER_PASSWORD=worker_pass
        - WEB_AUTHS=web_auth_user:web_auth_password
        - WORKERS=kernelci:pass
        - BUILDBOT_STATUS_TOKEN=gentoo_webhook
        - TCP_PORTS=8010,9989
    depends_on:
      - db
    links:
      - db
    ports:
      - 8010:8010
    expose:
      - 9989
    networks:
      - gkernelci-net



  db:
    image: "postgres:11.4-alpine"
    env_file: db.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gkernelci-net

  worker:
    build: 
        context: ./GBuildbot-worker
        args:
          LAVA_SERVER: lava_server:lava_port
          LAVA_TOKEN: lava_token
          LAVA_USER: lava_user
    environment:
        BUILDMASTER: master_ip
        BUILDMASTER_PORT: master_port
        WORKERNAME: worker_name
        WORKERPASS: worker_pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    volumes:
      - fileserver:/var/www/fileserver
      - worker_data:/buildbot
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gkernelci-net

  fileserver:
    build: ./Gfileserver
    ports:
      - 8080:8080
    volumes:
      - fileserver:/var/www/static
    networks:
      - gkernelci-net

volumes:
  db:
  certs:
  vhost.d:
  html:
  postgres_data:
  fileserver:
  worker_data:

networks:
  gkernelci-net:
