version: '3'
services:

  buildbot:
    image: gkernelci/buildbot-master:master
    build: gkernelci-master
    env_file: db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://github.com/aliceinwire/GKernelCI/archive/master.tar.gz
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=https://kernel1.amd64.dev.gentoo.org
        - BUILDBOT_WEB_PORT=8010
        - WEB_AUTHS=demo:demo
        - WORKERS=kernelci:pass
        - BUILDBOT_STATUS_TOKEN=example
        - TCP_PORTS=8010,9989
    links:
      - db
    expose:
        - 8010
        - 9989


  db:
    image: "postgres:11.4-alpine"
    env_file: db.env
    expose:
        - 5432
    volumes:
        - postgres_data:/var/lib/postgresql/data

  worker:
    image: buildbot/buildbot-worker:master
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: kernelci
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    volumes:
      - fileserver:/var/www/fileserver

  fileserver:
    build: ./Gfileserver
    ports:
      - 8080:8080
    volumes:
      - fileserver:/var/www/static

volumes:
  db:
  certs:
  vhost.d:
  html:
  postgres_data:
  fileserver:
